image: rocker/verse:latest

variables:
  DOCKER_DRIVER: "overlay2"
  GIT_SUBMODULE_STRATEGY: "recursive"
  R_LIBS: "${CI_PROJECT_DIR}/ci/R/library"
  R_PKGS: lubridate
  APT_PKGS: libssl-dev

cache:
  key: ${CI_JOB_NAME}
  paths:
    - ${R_LIBS}

before_script:
  - mkdir -p ${R_LIBS}
  - apt-get update

pages:
  stage: deploy
  script:
  - Rscript -e "bookdown::render_book('index.Rmd', 'all', output_dir = 'public')"
  artifacts:
    paths:
    - public
  only:
  - master
